### PR TITLE
Vendorsprites

### PR DESCRIPTION
**Pull request by Spacedong**
:cl: Spacedong
add: Changed vending machine sprites to those of pre-rebase.
/:cl:

Comparison of what they will be changed to:
New (the sprites they will be changed to): 

Current Sprites On The Live Server:

### CODE REVIEW

**Comment by JohnGinnane** [comment]
@Spacedong merge conflicts((

**Comment by cacogen** [comment]
haha my guy

**Comment by Spacedong** [comment]
Some checks haven’t completed yet
1 pending and 1 successful checks

**Comment by Spacedong** [comment]
Some checks haven’t completed yet
1 pending and 1 successful checks

**Comment by JamieH** [comment]
Reopen when you fix the conflict....

**Pull request closed without merging**
