### PR TITLE
Ported self-cryo back from before rebase

### LINKED ISSUE #406: Port back self-cryo
Being able to cryo self automatically by closing the door wasn't ported back. It should be.

### PR DESCRIPTION
**Pull request by Spacedong**
:cl: blute
add: You can now automatically activate a cryotube by standing inside it and pressing the Close button.
/:cl:

Fixes #406

### CODE REVIEW

**Comment by tortellinitony** [comment]
this isn't how it worked pre rebase

**Comment by JohnGinnane** [comment]
https://github.com/HippieStationCode/HippieStation13/blob/56a3fdddeb58b6e0dedb20514f4cc43bee628c58/code/ATMOSPHERICS/components/unary_devices/cryo.dm#L209

For reference

**Comment by JohnGinnane** [comment]
Not sure we need head input on this?

**Comment by Chnkr** [comment]
is this tested? Because this seems to now only close the machine if you close it yourself no?

**Comment by JohnGinnane** [comment]
no, close_machine() is still called. It just means it'll turn on if you happen to be the occupant

**Pull request merged**
