### PR TITLE
Ports Stand Arrow

### PR DESCRIPTION
**Pull request by yobob591**
https://www.youtube.com/watch?v=NFjE5A4UAJI

Functionally identical to pre-rebase stand arrow, only difference is that it uses all the new stands that /tg/ added

🆑 Yobob
add: Stand arrow is bacc
/🆑

### CODE REVIEW

**Comment by PopNotes** [comment]
It's a yes from me

**Comment by yobob591** [comment]
Ports is clearer cause stand arrow was never removed and was not altered in any way in this move

**Comment by tortellinitony** [comment]
nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnO

**Comment by KittyKathy** [comment]
Is that a JoJo reference? Jokes aside yeah this is good, but one thing will the meteor event spawn multiple stand arrows? Not saying it's a bad thing because it would be hard enough to find one with the station basically wrecked.

**Comment by yobob591** [comment]
I believe the higher level meteor events spawned more than 1 stand arrow, but normal events dont

**Comment by yobob591** [comment]
fug you guys borked it

**Comment by yobob591** [comment]
you niggers broke it

**Pull request closed without merging**
