### PR TITLE
Deters mimes from breaking their vow

### PR DESCRIPTION
**Pull request by Spacedong**
this kills the powergamer

### CODE REVIEW

**Comment by McBawbaggings** [comment]
Nah, talking mimes should be beaten, not killed. Break their spirits.

**Comment by Dudeinyourbackyard** [comment]
this is NO GOOD!!
mimes who talk are degenerates though

**Comment by Spacedong** [comment]
you're no good! you're outta here!

**Comment by KittyKathy** [comment]
How about you make it have like a 50% or something chance to gib instead because you are pretty much forcing them to not talk now as in they can't even if they wanted. If you are going to force them to not talk it would be better to just remove the break vow spell.

Also where is the Saltdong tag, did you even test this code? inb4 this gibs everyone near the mime including the mime.

`for(var/mob/living/carbon/human/H in targets)`
Do you know for certain that the targets list only has that mime who broke the vow in it seeing as you removed the checks to see if the mob is a mime?
What about other mimes around that mime because hop was stupid and opened a ton of mime slots?
why are you not using the `user` variable instead?

**Pull request closed without merging**
