### PR TITLE
SOMETHING WRONG, I HOLD MY HEAD, ARCLUMIN GONE, A NIGGA DEAD.

### PR DESCRIPTION
**Pull request by Spacedong**
:cl: Spacedong
add: Memorialized our fallen coder, ArcLumin, with a grave on the Centcom docks. May he rest in peace.
/:cl:

### CODE REVIEW

**Comment by Limed00d** [comment]
I would suggest putting it somewhere more noticeable honestly

**Comment by Spacedong** [comment]
everyone eventually goes there though, thats where the emergency shuttle docks

**Comment by oprayx77** [comment]
kind of a good spot except lazy, you should make a dirt floor asteroidy area atleast

**Comment by Spacedong** [comment]
can you sprite out the dirt and make it a block of stone?

**Comment by Spacedong** [comment]
@oprayx77

**Comment by Sarcalogo** [comment]
You shouldn't have content in game that references other players. I'm pretty sure you used this justification yourself Spacedong. Are you going to be a hypocrite?

"honestly these people didn't do anything noteworthy to warrant their place in the game code and as such they don't deserve to be immortalized here"

https://github.com/HippieStationCode/HippieStation13/pull/2821

**Comment by KittyKathy** [comment]
What happened to Arc?

**Comment by JohnGinnane** [comment]
Arc died in a car accident on Friday morning :(

**Comment by Iamgoofball** [comment]
@Sarcalogo 
Award for most edgy fuckwit goes to

**Comment by Sarcalogo** [comment]
What's wrong? Is there anything that I said that was not true? Spacedong IS being a hypocrite, he removed references from other players using the reasoning: "honestly these people didn't do anything noteworthy to warrant their place in the game code and as such they don't deserve to be immortalized here" What has this person done that is noteworthy? Dying? I can guarantee you more people knew about the people referenced before, (Hackole and Meteoses) than some literally who coder who never played the game.

Is it too much to ask that people don't contradict themselves?

**Comment by Chnkr** [comment]
@Sarcalogo both me and Jamie have added player references into the game since the rebase, i don't see anything wrong with this.

**Comment by JohnGinnane** [comment]
+1

**Comment by Iamgoofball** [comment]
@Sarcalogo are you too busy tipping your fedora to acknowledge that a member of the community has died

**Comment by Spacedong** [comment]
@Sarcalogo what the fuck is wrong with you?

**Comment by Chnkr** [comment]
```
Sarcalogo commented 26 minutes ago
What's wrong? Is there anything that I said that was not true? Spacedong IS being a hypocrite, he removed references from other players using the reasoning: "honestly these people didn't do anything noteworthy to warrant their place in the game code and as such they don't deserve to be immortalized here" What has this person done that is noteworthy? Dying? I can guarantee you more people knew about the people referenced before, (Hackole and Meteoses) than some literally who coder who never played the game.

Is it too much to ask that people don't contradict themselves?
```

Just preserving this, but good lord @Sarcalogo get the fuck out of here.

**Comment by TheFriggenSawbones** [comment]
why havent you guys perma'd sarca yet lmao

**Comment by blobbernaut** [comment]
Let's use goof's tomb design, it's pretty.

**Comment by Spacedong** [comment]
I am

**Comment by blobbernaut** [comment]
Also fuck you sarc

**Comment by JohnGinnane** [comment]
@Spacedong this ready?

**Comment by Spacedong** [comment]
yeet

**Comment by JamieH** [comment]
RIP Arc, you'll be missed man :(

**Comment by JamieH** [comment]
@Sarcalogo fuck off

**Comment by Iamgoofball** [comment]
did you perma him yet

**Comment by Sarcalogo** [comment]
You seem to be misunderstanding what I'm saying. While I personally think it's in poor taste, I don't care about the inclusion or exclusion of this memorial. Your friend died, it sucks, whatever, but that's not really relevant to what I'm saying.  I am pointing out that Spacedong is a hypocrite and made up a bunch of nonsensical standards that he himself doesn't adhere to, to spite people he doesn't like. If he honestly believed the things he says, this wouldn't exist. There's nothing wrong with pointing that out, no matter how many times you insult me.

Also worthy of note, plenty of other people have died playing this game, and have received no recognition whatsoever, which is partially why I think it is in poor taste. Where are their memorials?

**Comment by Iamgoofball** [comment]
we're actually working on that

**Comment by blobbernaut** [comment]
Pr a fucking memorial for them then,  sarc.

**Comment by PopNotes** [comment]
spacedong is a piece of shit but @Sarcalogo is an infinitely bigger piece of shit

**Comment by Sarcalogo** [comment]
M E M E N T O
M O R I

**Pull request merged**
