### PR TITLE
Old airlock sounds

### PR DESCRIPTION
**Pull request by Pyko1**
:cl: Pyko kills the wubwubwub
tweak: Changed the airlock close and denied sounds to the old ones.
fix: Clown door now honks on close as well.
/:cl:

### CODE REVIEW

**Comment by JohnGinnane** [comment]
Does this mean the airlock closing noise is now the old one? (the opening sound was fine)

**Comment by Pyko1** [comment]
yeah its the old one aka same as opening
 and the beep beep instead of wubwubwub when no access.

**Comment by JohnGinnane** [comment]
Cool, merging as it's oldcode then

**Comment by JohnGinnane** [comment]
Although, should we have the denied sound in the hippie folder?

**Comment by Pyko1** [comment]
No use really as the tg code had to be edited anyways.

**Comment by PopNotes** [comment]
But I liiiiiked the new airlock sounds.

**Pull request merged**
