### PR TITLE
fix starlight issue

### PR DESCRIPTION
**Pull request by ZachDeava**
Removed the unnecessary proc and moved the code to where it should be
more efficient. Fixes issue #56

### CODE REVIEW

**Comment by JohnGinnane** [comment]
Did you test this? Does it improve the speed of starting/restarting server?

**Comment by ZachDeava** [comment]
On my machine it reduced the loading time by about 80%.

**Comment by ZachDeava** [comment]
The issue wasn't with the starlight proc, there are other performance issues. Resolving them now.

**Comment by KittyKathy** [comment]
Will this fix all the 
`Cannot read null.starlight`
`pick() from empty list`
runtimes and starlight graphical issues?
Or are those unrelated issues?
That pick from empty list thing might be because of a change I made on something I am testing but I doubt that highly.

**Comment by JohnGinnane** [comment]
We're currently testing this now

**Comment by ZachDeava** [comment]
@KittyKathy It fixes that. Ended up being a mapping issue, will be resolved in a PR jamie is about to push

**Pull request closed without merging**
