### PR TITLE
Fixes getting in and out of the pool

### PR DESCRIPTION
**Pull request by tortellinitony**

### CODE REVIEW

**Comment by JamieH** [comment]
Did you test it @tortellinitony ?

**Comment by tortellinitony** [comment]
yes

**Comment by KittyKathy** [comment]
So with this can you actually rest in the pool now? Does this completely fix the pool as in there are no issues with it?

**Comment by tortellinitony** [comment]
no

**Comment by JohnGinnane** [comment]
Could you fix the issue where you can't breath in the pool?

This does fix getting in and out of the pool though, can you add "Fixes #30"?

**Comment by JohnGinnane** [comment]
This is the wrong repo, please open PR on correct one: https://github.com/HippieStation/HippieStation13-rebase

**Pull request closed without merging**
