### PR TITLE
Assliggers

### PR DESCRIPTION
**Pull request by yobob591**
Ashliggers spawn more as discussed in that issue thats on the WRONG FUCKING GITHUB

Anyways I set their spawn rate to cost 5 so they should spawn most rounds instead of almost never

### CODE REVIEW

**Comment by cacogen** [comment]
Did you test this? Because even setting it to 0, they only spawn about once every three.

**Comment by Pyko1** [comment]
yeah even if its free, it wont spawn if all points are used.

**Comment by BTFO** [comment]
fuck off

**Comment by Pyko1** [comment]
now thats constructive

**Comment by BTFO** [comment]
@Pyko1 we dont need more fucking ghost roles, being dead needs to feel bad man

**Comment by gumner** [comment]
>we dont need something for our dead players to do,if they die,go play on another server<

great,lowpop is great isnt it

**Comment by Pyko1** [comment]
naah it helps the server to keep population ashliggers arent a threat to the station at least now.

**Comment by Spacedong** [comment]
ashniggers

**Comment by yobob591** [comment]
they dont need to be every round anyways, just more than once every 20 rounds

**Comment by McBawbaggings** [comment]
Do we really need drones 2.0 when drones are already the ghost job?

**Comment by yobob591** [comment]
@McBawbaggings drones arent as fun cause you build instead of fight mobs

hippie players dont build, they only destroy

**Comment by yobob591** [comment]
if ashliggers stay as rare as they are they majorly need a buff, every time ive seen them which is almost never they get themselves killed or are killed by goliaths spawning on their shit like 2 minutes into the round

**Comment by yobob591** [comment]
give me the ligg

**Comment by Pyko1** [comment]
Unlike drones these guys arent messing the station.
And unlike drones these guys are at least somewhat entertaining.

Currently the spawn only happens around 1 out 5 rounds.
and with this its around once in 3 or 4 rounds.

**Comment by cacogen** [comment]
should probably remove the cost entirely tbh

and for the golem ruin too

**Comment by Pyko1** [comment]
swaarmers eating ashliggerbase

I mean once in a 5 rounds or shit and this kind of shit arent really that rare.

**Comment by cacogen** [comment]
that's like once every 5 hours, that's pretty rare unless you play all day

**Comment by yobob591** [comment]
once every 5 rounds is far better than once every 20 which it currently is

**Comment by cacogen** [comment]
yeah but i still think that isn't often enough. you should remove the cost from them entirely.

when i was testing the code for my now closed buff to ash walkers i had the cost removed and i had to run it at least three times before the ruin would spawn.

**Comment by JamieH** [comment]
build this

**Comment by JohnGinnane** [comment]
So did reducing the cost help to spawn them? Is this ready?

**Comment by cacogen** [comment]
it does. when i was testing my own pr at a cost of 0 they spawned about once every three rounds. the current rate is less than once every 5 rounds.

**Comment by cacogen** [comment]
what are we waiting on to get this pulled? it's such a minor change. i assume people are uncertain about how often this will actually make them spawn.

**Comment by Chnkr** [comment]
@cacogen I'm personally not pulling this because I'm against this change, we don't need more ghost roles, we need players to actually play the game and not fuck off into space.

**Comment by cacogen** [comment]
this doesn't constitute fucking off to space because people only play these roles when they aren't getting back into the round anyway. i'd much rather be cloned than play one of these shitty mining roles.

**Comment by Dudeinyourbackyard** [comment]
I'm OK with the odds, and they're a nice little novelty alternative to being dead.
+1

**Comment by Pyko1** [comment]
Anyways cost of 0 or 5 has the same chance to spawn nest, with 0 you will just have 5 more points left in budget to spawn more crap. As ruins spawner will keep firing as long as there are budget left or sanity reaches 0.

The price drop will usually just mean more ruins to spawn, the only increase to spawn chance comes when last ruin is spawned, and even then only if there is less than 20 points left.

To substantial increase on spawn chance we would need to make some changes to: https://github.com/HippieStation/HippieStation13/blob/master/code/modules/awaymissions/zlevel.dm

Or add a duplicate datum entry for more tickets to the lavalandlottery.
ie.
```
/datum/map_template/ruin/lavaland/ash_walker
	name = "Ash Walker Nest"
	id = "ash-walker"
	description = "A race of unbreathing lizards live here, that run faster than a human can, worship a broken dead city, and are capable of reproducing by something involving tentacles? \
	Probably best to stay clear."
	suffix = "lavaland_surface_ash_walker1.dmm"
	cost = 5
	allow_duplicates = FALSE

/datum/map_template/ruin/lavaland/ash_walker2
	name = "Ash Walker Nest"
	id = "ash-walker"
	description = "A race of unbreathing lizards live here, that run faster than a human can, worship a broken dead city, and are capable of reproducing by something involving tentacles? \
	Probably best to stay clear."
	suffix = "lavaland_surface_ash_walker1.dmm"
	cost = 5
	allow_duplicates = FALSE
```

**Comment by Chnkr** [comment]
Or we just, you know add more ruins instead of allowing one garbage ruin to spawn more often

**Comment by Pyko1** [comment]
We could do that, but the system still should have some kind of spawn chance weight in it too.

Also if you add 5 point ruins it will also increase the chance of spawning 0 point and 15 point ruins, along with 5 point ruins.

**Comment by cacogen** [comment]
wouldn't removing allow_duplicates achieve the same thing as duplicating the datum or adding a multiplier?

**Comment by Pyko1** [comment]
Removing the allow_duplicates would just allow it to be spawned again, if the ruin spawner has already spawned it once.

**Comment by cacogen** [comment]
>Anyways cost of 0 or 5 has the same chance to spawn nest

i don't get this. surely a lower cost should make it more likely to spawn? it randomly picks a ruin from the list and then checks if it can afford it. a lower cost would mean it'd be more likely to be able to afford it.

**Comment by Pyko1** [comment]
That is because it stops when the points are 0.
So to spawn 0 point ruin it will have to have a minimum of 5 points left, and if it picks 0 point ruin, then it will spawn it and then roll again for and only accept 5 or 0 point ruins until it spawns 5 point ruin or runs out of sanity.

So only difference with between 5 and 0 price is that 0 price leaves more points for remaining ruins that gat spawned.

So statistically there should be as much rounds with ashligger nests, but the total amount of ruins spawned would go up slightly.

**Comment by cacogen** [comment]
this pull changes the ruin cost from 20 to 5. which somehow didn't make a difference in its likelihood to spawn when i tested it.

**Comment by Pyko1** [comment]
Yeah its its pretty minor increase.
While 20 to 60 points left the odds for it to spawn for every ruin spawned is 1/(30 - the amount of spawned ruins that cant be duplicated).
At 15 points the chance is slightly increased as you you have only the 15 points or less ruins still on the list.
Same thing at 10 and 5 points.

So it might not even affect the spawn chance at all if you have 20 points left and it picks 20 point ruin.
Funny thing tho, making it cost 5 instead of 20 makes all other ruins spawn slightly more often statistically even when 20 or above points.

**Comment by JohnGinnane** [comment]
I guess it is more likely as you could end up with 10 points left, and with 20 cost you wouldn't get it, but now you can with 5, but it's still random

**Comment by Chnkr** [comment]
I'm still against this, but all the other options in the comments are garbage, heads are fine with it so let's just merge this

**Pull request merged**
