### PR TITLE
Adds a bottle of liquid uranium to the virology smart fridge.

### PR DESCRIPTION
**Pull request by Sarcalogo**
I had received complaints from virologists that this was not a good feature, making virologists get their own uranium, so I have changed it.

 :cl: Esumlogos
add: Virology now has a bottle of liquid uranium in it's smart fridge.
   /:cl:

### CODE REVIEW

**Comment by KittyKathy** [comment]
No, I was complaining miners were being shit by stealing the ore machine and dragging it to the mining base so they can get points without having to go back to the station which leaves the station with no minerals. There is a reason why they don't start with uranium because it can get level 8 symptoms which from reading the wiki should be op, but i have not seen it in the game yet to say if it actually is. I'm probably just going to make a system where they can get their points without coming on station but also send the ore to the station from the mining base.

**Comment by Sarcalogo** [comment]
The level 8 symptoms were the same symptoms you could get back in original virology though aren't they?

**Comment by KittyKathy** [comment]
No, tg virology is different now level 7 and 8 symptoms did not exist pre rebase. 

Level 8 symptoms are the super healing ones that do these things
1. Apoptoxin filter - Heals Toxin damage very quickly. 
2. Flesh Mending 	- Heals brute damage very quickly, and converts cellular damage into burn damage. 
3. Heat Resistance - Heals burn damage very quickly, and helps stabilize body temperature. 

Level 7 symptoms are super deadly ones that are designed to kill people like these
1. Acute Respiratory Distress Syndrome - Causes heavy suffocation damage, while giving a small chance of heart attacks. Becomes even more lethal if the mob has more than 120 suffocation damage. 
2. Alkali perspiration - Causes the affected mob to burst into flames periodically, while also giving them small doses of Napalm and Chlorine Trifluoride. 
3. Autophagocytosis Necrosis - Causes the mob's cells to decay rapidly, causing brute damage, constant bleeding and elevated hunger. 

That's pretty much the only uses for uranium in virology kinda op also it you need tons of uranium compared to plasma here is why each try for a level 7 symptom is 5 units of uranium and 1 unit of plasma. Each try for a level 8 symptom is 10 units of uranium and 1 units of plasma and 10 units of gold or sliver. 
Source: https://tgstation13.org/wiki/Infections

**Comment by McBawbaggings** [comment]
No thanks, the level 7 and 8 symptoms are very fucking potent.

**Comment by KittyKathy** [comment]
Actually I was wrong, it's even harder to get level 7 and 8 than I thought because I just tried it. You need 5 units to evolve a virus instead of 1 unit like the other chemicals. So for each attempt at a level 8 symptom it's going to need 5 units of Stable Uranium Gel which is 50 units of uranium and 50 units of sliver or gold and 5 units of plasma.

So 30 units is not much and is mostly going to be used for lethal viruses as you could probably make enough Unstable Uranium Gel to get a single level 7 symptom or instead make Decaying Uranium Gel which can give a level 6 or 7 and have 6 chances.

**Pull request closed without merging**
