### PR TITLE
Ports Dakimakuras from old codebase.

### PR DESCRIPTION
**Pull request by Sarcalogo**
:cl: Esumlogos
add: Dakimakuras are back in the game, reunite with your true love once more!
   /:cl:

### CODE REVIEW

**Comment by gumner** [comment]
when will we have johnny

**Comment by GuyonBroadway** [comment]
We need an option for a hippe daki... The bed just feels empty without him...

**Comment by KittyKathy** [comment]
What's this not adding security huds to the captains locker this time?
If your going to do add it to the captain locker, then the detective should get one too he is actually more apart of security than the captain yet he did not spawn with it in his locker pre rebase.

**Comment by Sarcalogo** [comment]
Kitty Kathy, you are very astute! You are right that I'm not adding SecHUDS this time, and there's a good reason for that. I can only tell you after this PR is merged, but it has to do with another PR I'm working on.

**Comment by Sarcalogo** [comment]
Or I can tell you now if you really want to know.

**Comment by Spacedong** [comment]
@gumner the johnny series?

**Comment by Sarcalogo** [comment]
It has a changelog.

**Comment by McBawbaggings** [comment]
the .yml functionality is now defunct.
Please refer to https://tgstation13.org/wiki/Guide_to_Changelogs on how to make changelogs.

**Comment by Sarcalogo** [comment]
https://tgstation13.org/wiki/Guide_to_Changelogs#Committing_a_.yml_file

Looks like the same thing, but whatever.

**Comment by Sarcalogo** [comment]
I dunno, what's going on here... I edited the description, did that work?

**Comment by McBawbaggings** [comment]
change "rscadd" to "add" and you should be golden.

**Comment by JamieH** [comment]
delete html/changelogs/Esumlogos.yml too

**Pull request merged**
