### PR TITLE
Ports "Majorly buff standard holoparas" (and fixes)

### PR DESCRIPTION
**Pull request by gumner**

### CODE REVIEW

**Comment by yobob591** [comment]
um i dont think we have holoparas so this does nothing

**Comment by gumner** [comment]
what?

**Comment by GuyonBroadway** [comment]
We jolly well do, it's just nobody has ever used them.

**Comment by yobob591** [comment]
uh no, they are unavailable for traitors

**Comment by GuyonBroadway** [comment]
I'm sure I saw them last time I was tator... In that case we should add them the fuck back in.

**Comment by McBawbaggings** [comment]
https://github.com/tgstation/tgstation/pull/18976
removed for being TOO FUN

**Comment by JohnGinnane** [comment]
This is the wrong repo, please open PR on correct one: https://github.com/HippieStation/HippieStation13-rebase

**Pull request closed without merging**
