### PR TITLE
Added three liberation stations to Centcom and a chainsword

### PR DESCRIPTION
**Pull request by Spacedong**
title

### CODE REVIEW

**Comment by tortellinitony** [comment]
redo it with map merger

**Comment by cacogen** [comment]
#43

**Comment by Sarcalogo** [comment]
I always hated those things, getting randomly one shot at centcom isn't fun. Post round griff should rely on what a person has acquired up to that particular point in the round.

**Comment by McBawbaggings** [comment]
Nah centcom armory was the best part of round end.

**Comment by Spacedong** [comment]
why aren't you merging this?

**Comment by cacogen** [comment]
you should add a picture so people know what they're merging

**Comment by Spacedong** [comment]
i did

**Comment by tortellinitony** [comment]
Redo this right with mapmerger so that you can read the changes in the file viewer...

**Comment by Chnkr** [comment]
@tortellinitony the mapmerger was used, it's just that the /tg/ mapmerger uses to do some dumb reshuffeling sometimes

**Comment by tortellinitony** [comment]
Put a screenshot then and I'll merge it

**Comment by Chnkr** [comment]
#249

**Pull request closed without merging**
