### PR TITLE
Revert "Adds scanner to science goggles to see object armour and damage values on examine"

### PR DESCRIPTION
**Pull request by Spacedong**
Fuck off powergaming retards

### CODE REVIEW

**Comment by PopNotes** [comment]
stop removing shit you don't like faggot

**Comment by JohnMcLaime** [comment]
You realise that they only give estimates which makes them not so useful, they should give exact values and people can check git for them anyway not like it is secret info you unrobust moron.

**Comment by cacogen** [comment]
what did he mean by this?

**Comment by Spacedong** [comment]
why do scientists get this ability roundstart though like for what purpose?

**Comment by Spacedong** [comment]
it makes literally no sense other than powergaming for a scientist of all people to have this at roundstart.

**Comment by PopNotes** [comment]
because it's totally a super powerful ability to have, basically on par with a possessed sword or chemistry amirite :^)))))))))

**Comment by Spacedong** [comment]
popnotes you're out of line faggot I'm moving out of your basement if you say one more thing like that

**Comment by PopNotes** [comment]
your reverts are shit and you're not contributing anything by undoing other people's work just because you personally dislike the additions

**Comment by Spacedong** [comment]
they objectively make no sense though

**Comment by JohnGinnane** [comment]
@Spacedong the PR was up for 3 days being worked on. It was originally all players, then given to sechud and we decided it would be more suitable (and less bullshit) for science to have it:

https://github.com/HippieStation/HippieStation13/pull/86

**Comment by Spacedong** [comment]
but why do civilian personnel like science need to know armor values? sechuds would make more sense.

**Comment by cacogen** [comment]
we added it to the science goggles to give them further value as a choice of eyewear instead of lumping all value into the secHUDs as I'd originally intended

chemists spawn with them as well, and there are two sitting in chemistry behind a windoor, so they're not hard to come by

**Comment by JohnGinnane** [comment]
Because science goggles should give you some insight to what an item can do, sechud already has wanted and implanted indicators, and would buff sec

**Comment by KittyKathy** [comment]
Saltdong? am I right or what? inb4 he closes this like 1 hour later.
I don't see why you need to remove this the googles being useful for things other than chemistry and research makes them valuable to other departments mainly security and newbies. Like how else would you know in game as a security officer that your jumpsuit has a slight melee protection(like 10).

**Comment by cacogen** [comment]
rip

**Pull request closed without merging**
