### PR TITLE
Ranged Stun Duration Test

### PR DESCRIPTION
**Pull request by ghost**
Take 3: Actually on the live repo this time.

Reduces duration of stuns from the electrode projectile from 5 to 3. Should reduce the stun times enough that a beaten down or tired target will be down just long enough to cuff, but anyone else will need either a melee stun or krav maga pin. This is just a short one or two week test to see how the playerbase reacts to to changes in the combat meta, so that we can collect data for large scale overhauls. This test will show us how the playerbase changes the meta to adapt to the changes, as well as how they react beyond combat. The end goal is an overhaul to ranged stuns which will please the majority of players, without completely alienating the powergamers and their cults of personality to the point that the server population drops.

🆑 QuarianCommando
tweak: Adjusted stun duration on ranged stuns. Ranged stuns will now require a follow up melee stun or krav maga pin to cuff your target. These changes are temporary, and for testing purposes.
/🆑

### CODE REVIEW

**Comment by PopNotes** [comment]
Im gay

**Comment by ghost** [comment]
I did it. It's actually in the proper repo, and not one of the half dozen legacy repos hanging around out there.

**Comment by Sarcalogo** [comment]
Do you not see the giant CODE FREEZE you idiot?

**Comment by Sarcalogo** [comment]
And by the way, if you nerf tasers like this, people are just going to switch to syringe guns, which have infinite range. Great going! Nerfing sec even more, making it actually impossible to do their job.

**Comment by ghost** [comment]
@Sarcalogo

I've already discussed this with Jamie, and he gave me the OK to push this to the live repository, seeing as this is a temporary test. It's just a whole lot cleaner to push this in here so the next rebate can overwrite it instead of having to go through all the trouble of writing this to the new repository's standards just do it can be reverted when the test is complete.

**Comment by Sarcalogo** [comment]
Wow, Jamie is an idiot, making some concessions for some idiot who doesn't understand basic game balance. Your temporary test is shit, why don't you actually play Security and see for yourself?

**Comment by ghost** [comment]
Additionally, everything you described is exactly what I want. I want people to scramble around finding new ways to power game. I want people to adapt to the changes. Everything the players do to work with or around this is data which can be used when writing future reworks of the stun and combat system. I'm taking advantage of the fact that this code base is being abandoned to run some last minute tests.

**Comment by ghost** [comment]
If you can't see the value of having hard data to turn back to for future updates, instead of giving in to the communities bitching and just slapping on more broken systems to counter another broken system, then you really don't have any footing when you call me an idiot who doesn't understand balance.

**Comment by Sarcalogo** [comment]
The combat system doesn't need to be reworked, it is balanced as it is. You are just pointlessly making it harder for Security to do their jobs.

 See: https://hippiestation.com/threads/putting-the-biggest-memes-to-rest-warning-requires-reading-decent-iq.6285/#post-51557

I guess I should finish writing this.

**Comment by ghost** [comment]
Your input has been noted, as always. However, your input is also horse shit. If the combat was never an issue, we never would have had to deal with the absolute clusterfuck that was anti-stuns. There is nothing wrong with prodding around to see what parts of the system in particular are broken so that they can be fixed with minimal collateral damage.

**Comment by Sarcalogo** [comment]
I'm not defending anti-stuns. Anti-stuns should be removed. You remove anti-stuns and there are no problems left.

**Comment by Sarcalogo** [comment]
But if you think anti-stuns are a problem, why on EARTH are you shortening stun times?

**Comment by Sarcalogo** [comment]
If you wanted to do a REAL fruitful test, you would remove all stuns from the game entirely.

**Comment by KayeArray** [comment]
h-hey kid, you see that variable called nodamage?

set it to 0

**Comment by ghost** [comment]
Anti-stuns would never have made it past the maintainers if stuns themselves didn't have any issues. I'm not saying that stuns are more broken than anti-stuns were, just that they do have some issues and that there's nothing wrong with running some tests to see what can be changed to improve the system as a whole. I understand that reducing stun duration won't fix anything by itself, but I want to see what effect that change specifically has. If all goes well with this PR, then the next test would be reducing taser capacity with original stun duration, them testing would be over. Poof, everything is the way it used to be and we get hard data to work with.

**Comment by ghost** [comment]
@banthebantz

Hey man, it was like that when I found it. The test is only to see what reducing stun times does. Making more changes outside of that would tamper with muh data.

**Comment by Sarcalogo** [comment]
Stuns don't have any issues at all.

**Comment by PopNotes** [comment]
Stuns have issues. Approve and merge, do not give the retard credence.

**Comment by Sarcalogo** [comment]
Actually, go right ahead and make whatever changes you want, I guess I have to resume my break(that I just came back from today. I feel like this is another "real communism hasn't been tried" deal, and we just have to let you retards run around killing a few million people before you realize that your plans are dumb and your ideology flawed.  I'm content to let you run around making haphazard changes until you've gotten yourselves into another rut where the entire system is JUST fucked. You guys are dumb and won't realize it for months, and even more people will quit playing.

**Comment by Sarcalogo** [comment]
@PopNotes 
Offer an argument here, if you are so great. 

https://hippiestation.com/threads/putting-the-biggest-memes-to-rest-warning-requires-reading-decent-iq.6285/#post-51557

All you did was write a sentence without any logical backing.

**Comment by ghost** [comment]
Does that mean we don't have to deal with your autistic screeching any time someone wants to make any sort of change to game balance? Can you take your friends with you? That would make this job a lot easier.

**Comment by Sarcalogo** [comment]
You didn't actually offer an argument either, I made a forum thread where I detailed exactly why stuns were necessary and you didn't post any counter arguments either. I'm not having a discussion on GitHub.

**Comment by PopNotes** [comment]
your input is shit
nobody gives a fuck
go away

**Comment by Sarcalogo** [comment]
Not an argument.

**Comment by ghost** [comment]
We're beyond arguments at this point. I've already made it clear that the entire purpose of this PR is the first step in figuring out exactly what's wrong with combat so that it can be properly fixed, instead of having a other one of those SS13 brand bandaids applied that ends up making everything worse until it's ripped off. You are arguing against the collection of data which will be used for the betterment of the server, regardless of the outcome of the test. Even if it turns out that duration isn't an issue, which it might not be, at least I had the balls to test it and we'll know not to touch it. Or it could be the complete opposite, and we might not even need further changes beyond reducing duration. More than likely it's in the middle, and a series of tests like this one will let us know how to perfect the system in the long run using hard data instead of feedback from people who all, regardless of if they intend it or not, have their own agenda to push.

**Comment by ghost** [comment]
@Iamgoofball

Do you have any input?

**Comment by Iamgoofball** [comment]
i don't see the problem

# but im still mad you removed every drug just because they had an easily disable anti-stun

**Comment by Iamgoofball** [comment]
also wrong codebase

**Comment by ghost** [comment]
If you mean the summoning of the Lord of another codebase, I just wanted input. 

If you mean the repo, this is our live repo. We have a code freeze to make the porting of hippie features to the rebase easier without more work piling up.

**Comment by Sarcalogo** [comment]
\>We're beyond arguments at this point.

No, arguments are necessary to determine what exactly is going to happen, and what has happened. I gave you a long argument in that forum post about what would happen if you were to remove stuns. My arguments are incredibly strong, and border more on truth than argumentation. If nobody can make a counter argument, it means that I am right. If someone can, and I can't argue against it, it means that I'm wrong. That's why we have arguments, to determine the truth. 

I'm telling you right now that if you reduce stun durations the only thing you are going to do is make it harder for Security to do their jobs, making it easier to greytide and kill people. If it's easy to greytide and murder, greytide and murder will become more common. That's a very basic argument, if you think about it, it becomes more complex.

\> in figuring out exactly what's wrong with combat

And what makes you think there is something wrong in the first place? You mentioned antistuns, but then wouldn't you think that you already know what the problem was, antistuns?

\>You are arguing against the collection of data which will be used for the betterment of the server, regardless of the outcome of the test.

To actually understand the results of the test, you need people to articulate what they thought the results of the test were. You could interpret it one way, while someone else another way. This is another reason why arguments are necessary. By showing yourselves as people who refuse to sit down and have a discussion about it, it makes me doubt whether you will be able to accurately assess the situation at all. It could be that @PopNotes  is just butthurt that he sucks at dodging taser shots and wants to remove them all at any cost. Maybe he doesn't care about any negative consequences that has because he enjoys murdering and greytiding. The point is, I don't trust your judgment, I don't trust most people's judgment. That's why anti-stuns existed for so long. It'll be just a test, huh? Say one thing, yet do another. That's what I think. 

\>Even if it turns out that duration isn't an issue, which it might not be, at least I had the balls to test it and we'll know not to touch it.

I know from experience not to touch it, here I am telling you and you are ignoring me. If you are ignoring me, why should anyone in the future listen to you when you tell them it doesn't work? The same thing happened with anti-stuns. People were screaming and shouting about how cancerous they are and that fixing them does nothing, but nobody listens. No, no, no, you see MY specific anti-stun solution hasn't been tried yet, so we're going to do it RIGHT NOW! That's exactly what will happen in the future. Nobody will care about, listen, or remember the results of this test.

\>in the long run using hard data

And what exactly is hard data in this scenario?

**Comment by PopNotes** [comment]
"My arguments are incredibly strong, and border more on truth than argumentation"

stopped reading right there
out

**Comment by Sarcalogo** [comment]
Also not an argument.

**Comment by PopNotes** [comment]
out

**Comment by ghost** [comment]
I've just been brought up to speed on a few things regarding Sarcalogo, and their history on hippie station as well as other servers. I would like to ask anyone just coming into this discussion to politely ignore the retarded child standing in the corner shouting obscenities. From what I've been told, he is currently blacklisted from at least two /tg/ based servers, and several hippie admins seem to remember him being permabanned at some point. Let's try to keep this PR page as clean as possible, and keep any arguments on our respective server's forums.

**Comment by Sarcalogo** [comment]
Not an argument QuarianCommando. Do you have any counterarguments whatsoever?

**Comment by ghost** [comment]
I'm done arguing. I don't want to argue here, and I don't want you arguing with everyone here. Please leave.

**Comment by Sarcalogo** [comment]
You can't be done if you never started :^). Prove me right boyo, prove me right.

**Comment by Iamgoofball** [comment]
hey sarca aren't you busy jerking off because a community member died

**Comment by Sarcalogo** [comment]
Yeah, Joshua Pain. Dead and forgotten by all but me. No statue for him though.

**Comment by GuyonBroadway** [comment]
Counterargument to sec not being able to do their jobs.

Tase -> quick baton followup -> cuffs.

Tasers are bad because one donk can kill about three people with one taser and a botany hatchet before ever needing to recharge said taser. Four, if none of these people had armour with better melee protection than sec armour.

**Comment by ghost** [comment]
People might actually bother upgrading the cell in their stun batons now.

**Comment by JohnMcLaime** [comment]
Doesnt change much, 1 hit with taser bolt will generally still get you a frag, time reduction like that isnt that impactful, since you can easily do a followup stun with taser/disabler while beating shit out of them in intervals.
Nerfing stuns is a right way to a healthy combat system though.

> @PopNotes is just butthurt that he sucks at dodging taser shots and wants to remove them all at any cost. 

Is one of the stupidest arguments you could come up with. I thought you were a reasonable person. Dodging shots isnt exclusive to tasers only, besides they can dual wield guns against you, yes they get rng dispersion/accuracy but that also makes it harder for enemy to dodge. Dodging works against other ranged weapons too, but dodging is the only counter you really had for the most time 1 hit stuns were around or hitting the other guy first. While to counter hp damaging guns you got a bunch of chems, instant heals, armor ("energy" resistances on most armors wont make a difference if you get stunned, unless it was their last shot or some shit) and ofcourse they dont gg no re you in one hit and they give you time to fight back, with heals, retaliation or falling back. There really arent 1 hit instakill easily aqquirable guns, besides tasers/stunners.
For me it looks like you are afraid of changes to your easy way of winning, just grabbing a taser and having a wild west shootout contest. Instead for more variable, meaningful and prolonged fights, you decide to drool in closet/disposals chute with taser in one hand and dick in the other, while fishing for targets to come by or just mindlessly charging places with that equipment.

**Comment by j-mie** [comment]
I still think the solution is to remove all ranged stuns and do stamina damage in-place of that.

**Comment by Iamgoofball** [comment]
# this is still the wrong github

**Comment by ghost** [comment]
Goofball, we've been over this.

**Pull request closed without merging**
