### PR TITLE
Mapfixes

### PR DESCRIPTION
**Pull request by Pyko1**
:cl: Mapfix
fix: Warmed up the atmos tanks
add: Added soul contracts and other TG map stuff around the law office.
add: Added Codex Gigas to library.
add: Added Drone Fabricator to misc lab.
/:cl:

Fixes: https://github.com/HippieStation/HippieStation13/issues/69
Fixes: https://github.com/HippieStation/HippieStation13/issues/68
Fixes: https://github.com/HippieStation/HippieStation13/issues/51
Fixes: https://github.com/HippieStation/HippieStation13/issues/48

### CODE REVIEW

**Comment by JohnGinnane** [comment]
Is this branch, https://github.com/Pyko1/HippieStation13/tree/mapping, the one you're working on?

**Comment by Pyko1** [comment]
should be

**Comment by JohnGinnane** [comment]
Cool, I might just clone it and test those things

**Comment by JohnGinnane** [comment]
This is the wrong repo, please open PR on correct one: https://github.com/HippieStation/HippieStation13-rebase

**Pull request closed without merging**
